In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns',None)

In [2]:
attack =  pd.read_csv("C:/Users/rajen/Data Analysis/UCL 2021-22 data analysis/attacking.csv")
attempt = pd.read_csv("C:/Users/rajen/Data Analysis/UCL 2021-22 data analysis/attempts.csv")
defend =  pd.read_csv("C:/Users/rajen/Data Analysis/UCL 2021-22 data analysis/defending.csv")
disc = pd.read_csv("C:/Users/rajen/Data Analysis/UCL 2021-22 data analysis/disciplinary.csv")
distri = pd.read_csv("C:/Users/rajen/Data Analysis/UCL 2021-22 data analysis/distributon.csv")
goalkeep = pd.read_csv("C:/Users/rajen/Data Analysis/UCL 2021-22 data analysis/goalkeeping.csv")
goal = pd.read_csv("C:/Users/rajen/Data Analysis/UCL 2021-22 data analysis/goals.csv")
stats =  pd.read_csv("C:/Users/rajen/Data Analysis/UCL 2021-22 data analysis/key_stats.csv")

In [6]:
attack.head()

,serial,player_name,club,position,assists,corner_taken,offsides,dribbles,match_played
0,1,Bruno Fernandes,Man. United,Midfielder,7,10,2,7,7
1,2,Vinícius Júnior,Real Madrid,Forward,6,3,4,83,13
2,2,Sané,Bayern,Midfielder,6,3,3,32,10
3,4,Antony,Ajax,Forward,5,3,4,28,7
4,5,Alexander-Arnold,Liverpool,Defender,4,36,0,9,9

In [9]:
attempt.head()

,serial,player_name,club,position,total_attempts,on_target,off_target,blocked,match_played
0,1,Benzema,Real Madrid,Forward,45,23,13,9,12
1,2,Salah,Liverpool,Forward,42,22,11,9,13
2,3,Mahrez,Man. City,Midfielder,37,18,8,11,12
3,4,Sané,Bayern,Midfielder,33,13,12,8,10
4,5,Lewandowski,Bayern,Forward,31,19,8,4,10

In [10]:
defend.head()

,serial,player_name,club,position,balls_recoverd,tackles,t_won,t_lost,clearance_attempted,match_played
0,1,Casemiro,Real Madrid,Midfielder,76,31,13,18,19,11
1,1,Éder Militão,Real Madrid,Defender,76,19,6,13,32,12
2,1,Reinildo,Atlético,Defender,76,13,6,7,20,10
3,4,Fabinho,Liverpool,Midfielder,74,23,9,14,8,13
4,5,Albiol,Villarreal,Defender,73,9,6,3,62,12

In [12]:
disc.head()

,serial,player_name,club,position,fouls_committed,fouls_suffered,red,yellow,minutes_played,match_played
0,1,João Palhinha,Sporting CP,Midfielder,23,17,2,0,534,6
1,2,Capoue,Villarreal,Midfielder,19,17,3,1,1046,12
2,2,Rodri,Man. City,Midfielder,19,4,2,0,842,10
3,2,Seiwald,Salzburg,Midfielder,19,3,2,0,649,8
4,5,Balanta,Club Brugge,Midfielder,18,3,4,0,407,5

In [13]:
distri.head()

,serial,player_name,club,position,pass_accuracy,pass_attempted,pass_completed,cross_accuracy,cross_attempted,cross_complted,freekicks_taken,match_played
0,1,Erokhin,Zenit,Midfielder,98.0,27,26,0,2,0,0,6
1,2,Eric García,Barcelona,Defender,97.5,203,197,0,0,0,1,4
2,3,Ulreich,Bayern,Goalkeeper,97.0,32,31,0,0,0,1,1
3,4,Rugani,Juventus,Defender,96.8,130,122,0,0,0,0,4
4,5,J. Timber,Ajax,Midfielder,95.8,497,474,0,1,0,14,8

In [14]:
goalkeep.head()

,serial,player_name,club,position,saved,conceded,saved_penalties,cleansheets,punches made,match_played
0,1,Courtois,Real Madrid,Goalkeeper,61,14,1,5,4,13
1,2,Rulli,Villarreal,Goalkeeper,41,16,0,3,12,12
2,3,Vlachodimos,Benfica,Goalkeeper,38,17,1,5,5,10
3,4,Athanasiadis,Sheriff,Goalkeeper,29,8,0,1,2,5
4,5,Mignolet,Club Brugge,Goalkeeper,28,20,0,0,1,6

In [15]:
goal.head()

,serial,player_name,club,position,goals,right_foot,left_foot,headers,others,inside_area,outside_areas,penalties,match_played
0,1,Benzema,Real Madrid,Forward,15,11,1,3,0,13,2,3,12
1,2,Lewandowski,Bayern,Forward,13,8,3,1,1,13,0,3,10
2,3,Haller,Ajax,Forward,11,3,4,3,1,11,0,1,8
3,4,Salah,Liverpool,Forward,8,0,8,0,0,7,1,1,13
4,5,Nkunku,Leipzig,Midfielder,7,3,1,3,0,7,0,0,6

In [16]:
stats.head()

,player_name,club,position,minutes_played,match_played,goals,assists,distance_covered
0,Courtois,Real Madrid,Goalkeeper,1230,13,0,0,64.2
1,Vinícius Júnior,Real Madrid,Forward,1199,13,4,6,133.0
2,Benzema,Real Madrid,Forward,1106,12,15,1,121.5
3,Modrić,Real Madrid,Midfielder,1077,13,0,4,124.5
4,Éder Militão,Real Madrid,Defender,1076,12,0,0,110.4

In [87]:
pd.concat([attack,attempt,distri,disc,goalkeep,goal,stats]).drop_duplicates(subset = ['player_name'],keep = 'first').player_name.nunique()

732

In [22]:
goal.player_name

0             Benzema
1         Lewandowski
2              Haller
3               Salah
4              Nkunku
            ...
178           Yansané
179       Yakhshiboev
180    Messias Junior
181            Morato
182       Pedro Porro
Name: player_name, Length: 183, dtype: object

In [37]:
mg1 = pd.merge(stats,goal,how = 'left')

In [51]:
list(stats.player_name) == list(goal.player_name)

False

In [49]:
pd.merge(mg1,goalkeep,how = 'right')

,player_name,club,position,minutes_played,match_played,goals,assists,distance_covered,serial,right_foot,left_foot,headers,others,inside_area,outside_areas,penalties,saved,conceded,saved_penalties,cleansheets,punches made
0,Courtois,Real Madrid,Goalkeeper,NaN,13,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61,14,1,5,4
1,Rulli,Villarreal,Goalkeeper,NaN,12,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41,16,0,3,12
2,Vlachodimos,Benfica,Goalkeeper,NaN,10,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38,17,1,5,5
3,Athanasiadis,Sheriff,Goalkeeper,NaN,5,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29,8,0,1,2
4,Mignolet,Club Brugge,Goalkeeper,NaN,6,NaN,NaN,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28,20,0,0,1
5,Oblak,Atlético,Goalkeeper,NaN,10,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26,10,0,3,2
6,Musso,Atalanta,Goalkeeper,NaN,6,NaN,NaN,NaN,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21,13,0,1,1
7,Ersin Destanoğlu,Beşiktaş,Goalkeeper,NaN,5,NaN,NaN,NaN,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20,17,0,0,0
8,De Gea,Man. United,Goalkeeper,NaN,7,NaN,NaN,NaN,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19,9,0,1,0
9,Dahlin,Malmö,Goalkeeper,NaN,4,NaN,NaN,NaN,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19,8,1,0,3
10,Diogo Costa,Porto,Goalkeeper,NaN,6,NaN,NaN,NaN,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18,11,0,2,2
11,Trubin,Shakhtar Donetsk,Goalkeeper,NaN,3,NaN,NaN,NaN,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18,9,0,0,0
12,Casteels,Wolfsburg,Goalkeeper,NaN,5,NaN,NaN,NaN,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18,8,0,1,2
13,Donnarumma,Paris,Goalkeeper,NaN,5,NaN,NaN,NaN,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18,6,1,2,9
14,Adán,Sporting CP,Goalkeeper,NaN,7,NaN,NaN,NaN,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17,13,0,2,8
15,Köhn,Salzburg,Goalkeeper,NaN,8,NaN,NaN,NaN,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,14,0,1,3
16,Ter Stegen,Barcelona,Goalkeeper,NaN,6,NaN,NaN,NaN,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,9,0,3,2
17,Alisson Becker,Liverpool,Goalkeeper,NaN,13,NaN,NaN,NaN,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,14,0,4,3
18,Ederson,Man. City,Goalkeeper,NaN,11,NaN,NaN,NaN,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14,14,0,4,1
19,Kobel,Dortmund,Goalkeeper,NaN,6,NaN,NaN,NaN,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14,11,1,2,1
20,Szczęsny,Juventus,Goalkeeper,NaN,7,NaN,NaN,NaN,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14,10,0,3,3
21,Maignan,Milan,Goalkeeper,NaN,3,NaN,NaN,NaN,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14,7,1,0,1
22,Neuer,Bayern,Goalkeeper,NaN,9,NaN,NaN,NaN,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14,6,0,4,1
23,Bounou,Sevilla,Goalkeeper,NaN,6,NaN,NaN,NaN,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14,5,0,2,1
24,Bushchan,Dynamo Kyiv,Goalkeeper,NaN,5,NaN,NaN,NaN,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13,11,0,0,4
25,Pasveer,Ajax,Goalkeeper,NaN,6,NaN,NaN,NaN,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13,6,0,2,2
26,Diawara,Malmö,Goalkeeper,NaN,3,NaN,NaN,NaN,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13,6,0,0,1
27,Grbić,LOSC,Goalkeeper,NaN,6,NaN,NaN,NaN,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13,4,0,3,1
28,Handanovič,Inter,Goalkeeper,NaN,8,NaN,NaN,NaN,29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,7,0,3,5
29,Kritsyuk,Zenit,Goalkeeper,NaN,4,NaN,NaN,NaN,29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,6,0,1,10
30,Faivre,Young Boys,Goalkeeper,NaN,3,NaN,NaN,NaN,29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,6,0,0,1
31,Gulácsi,Leipzig,Goalkeeper,NaN,5,NaN,NaN,NaN,32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,14,0,0,0
32,Navas,Paris,Goalkeeper,NaN,3,NaN,NaN,NaN,32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,5,0,0,3
33,Mendy,Chelsea,Goalkeeper,NaN,9,NaN,NaN,NaN,34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,7,0,5,2
34,Von Ballmoos,Young Boys,Goalkeeper,NaN,3,NaN,NaN,NaN,34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,6,0,0,1
35,Tătăruşanu,Milan,Goalkeeper,NaN,3,NaN,NaN,NaN,36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,2,0,1,2
36,Celeadnic,Sheriff,Goalkeeper,NaN,1,NaN,NaN,NaN,37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,3,0,0,1
37,M. Kerzhakov,Zenit,Goalkeeper,NaN,2,NaN,NaN,NaN,38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,4,0,0,0
38,Pyatov,Shakhtar Donetsk,Goalkeeper,NaN,3,NaN,NaN,NaN,38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,2,0,2,4
39,Pervan,Wolfsburg,Goalkeeper,NaN,1,NaN,NaN,NaN,38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,2,0,0,0
40,Leo Jardim,LOSC,Goalkeeper,NaN,2,NaN,NaN,NaN,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,4,0,0,0
41,Kepa,Chelsea,Goalkeeper,NaN,1,NaN,NaN,NaN,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,3,0,0,0
42,Günok,Beşiktaş,Goalkeeper,NaN,1,NaN,NaN,NaN,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,2,0,0,0
43,Ulreich,Bayern,Goalkeeper,NaN,1,NaN,NaN,NaN,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,1,0,0,2
44,Boyko,Dynamo Kyiv,Goalkeeper,NaN,1,NaN,NaN,NaN,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,0,0,1,2
45,João Virginia,Sporting CP,Goalkeeper,NaN,1,NaN,NaN,NaN,46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,4,0,0,0
46,Steffen,Man. City,Goalkeeper,NaN,1,NaN,NaN,NaN,46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,2,0,0,1
47,Henderson,Man. United,Goalkeeper,NaN,1,NaN,NaN,NaN,46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,1,0,0,1
48,Martínez,Leipzig,Goalkeeper,NaN,1,NaN,NaN,NaN,46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0,0,1,0
49,Onana,Ajax,Goalkeeper,NaN,2,NaN,NaN,NaN,50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,0,0,0
50,Perin,Juventus,Goalkeeper,NaN,1,NaN,NaN,NaN,50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,0,0,1,0
51,Shevchenko,Shakhtar Donetsk,Goalkeeper,NaN,1,NaN,NaN,NaN,52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,0,0,0
52,Carson,Man. City,Goalkeeper,NaN,1,NaN,NaN,NaN,52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0,1,0

In [48]:
mg1

,player_name,club,position,minutes_played,match_played,goals,assists,distance_covered,serial,right_foot,left_foot,headers,others,inside_area,outside_areas,penalties
0,Courtois,Real Madrid,Goalkeeper,1230,13,0,0,64.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Vinícius Júnior,Real Madrid,Forward,1199,13,4,6,133.0,16.0,3.0,1.0,0.0,0.0,4.0,0.0,0.0
2,Benzema,Real Madrid,Forward,1106,12,15,1,121.5,1.0,11.0,1.0,3.0,0.0,13.0,2.0,3.0
3,Modrić,Real Madrid,Midfielder,1077,13,0,4,124.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Éder Militão,Real Madrid,Defender,1076,12,0,0,110.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
742,Gil Dias,Benfica,Midfielder,1,1,0,0,0.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
743,Rodrigo Ribeiro,Sporting CP,Forward,1,1,0,0,0.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
744,Cojocari,Sheriff,Defender,1,1,0,0,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
745,Maouassa,Club Brugge,Defender,1,1,0,0,0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
746,Zesiger,Young Boys,Defender,1,1,0,0,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
stats.head()

,player_name,club,position,minutes_played,match_played,goals,assists,distance_covered
0,Courtois,Real Madrid,Goalkeeper,1230,13,0,0,64.2
1,Vinícius Júnior,Real Madrid,Forward,1199,13,4,6,133.0
2,Benzema,Real Madrid,Forward,1106,12,15,1,121.5
3,Modrić,Real Madrid,Midfielder,1077,13,0,4,124.5
4,Éder Militão,Real Madrid,Defender,1076,12,0,0,110.4

In [55]:
mg2 = pd.merge(stats,goalkeep,how = 'left')

In [62]:
pd.merge(stats,goal,how ='inner')

,player_name,club,position,minutes_played,match_played,goals,assists,distance_covered,serial,right_foot,left_foot,headers,others,inside_area,outside_areas,penalties
0,Vinícius Júnior,Real Madrid,Forward,1199,13,4,6,133.0,16,3,1,0,0,4,0,0
1,Benzema,Real Madrid,Forward,1106,12,15,1,121.5,1,11,1,3,0,13,2,3
2,Alaba,Real Madrid,Defender,1040,12,1,0,112.3,73,0,1,0,0,0,1,0
3,Kroos,Real Madrid,Midfielder,902,12,2,0,116.5,43,1,1,0,0,0,2,0
4,Asensio,Real Madrid,Forward,207,8,1,2,28.4,73,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174,Alcácer,Villarreal,Forward,73,3,1,0,10,73,1,0,0,0,1,0,0
175,Choupo-Moting,Bayern,Midfielder,49,4,1,0,6.7,73,0,0,1,0,1,0,0
176,Palmer,Man. City,Midfielder,40,3,1,0,7,73,0,1,0,0,1,0,0
177,Kjærgaard,Salzburg,Midfielder,38,4,1,0,7.9,73,0,1,0,0,1,0,0
178,Ozdoev,Zenit,Midfielder,11,1,1,0,2.2,73,1,0,0,0,0,1,0

In [63]:
pd.merge(stats,goalkeep,how = 'inner')

,player_name,club,position,minutes_played,match_played,goals,assists,distance_covered,serial,saved,conceded,saved_penalties,cleansheets,punches made
0,Courtois,Real Madrid,Goalkeeper,1230,13,0,0,64.2,1,61,14,1,5,4
1,Alisson Becker,Liverpool,Goalkeeper,1170,13,0,0,68.8,18,15,14,0,4,3
2,Rulli,Villarreal,Goalkeeper,1080,12,0,0,61.2,2,41,16,0,3,12
3,Ederson,Man. City,Goalkeeper,1003,11,0,0,51.6,19,14,14,0,4,1
4,Vlachodimos,Benfica,Goalkeeper,900,10,0,0,55.4,3,38,17,1,5,5
5,Oblak,Atlético,Goalkeeper,900,10,0,0,52.7,6,26,10,0,3,2
6,Mendy,Chelsea,Goalkeeper,840,9,0,0,57.4,34,9,7,0,5,2
7,Neuer,Bayern,Goalkeeper,810,9,0,1,51.2,19,14,6,0,4,1
8,Köhn,Salzburg,Goalkeeper,720,8,0,0,43.8,16,16,14,0,1,3
9,Handanovič,Inter,Goalkeeper,720,8,0,0,32,29,12,7,0,3,5
10,Adán,Sporting CP,Goalkeeper,630,7,0,0,36.3,15,17,13,0,2,8
11,Szczęsny,Juventus,Goalkeeper,630,7,0,0,31.4,19,14,10,0,3,3
12,De Gea,Man. United,Goalkeeper,630,7,0,0,26.4,9,19,9,0,1,0
13,Bounou,Sevilla,Goalkeeper,540,6,0,0,37.2,19,14,5,0,2,1
14,Kobel,Dortmund,Goalkeeper,540,6,0,0,35.4,19,14,11,1,2,1
15,Mignolet,Club Brugge,Goalkeeper,540,6,0,0,33.2,5,28,20,0,0,1
16,Musso,Atalanta,Goalkeeper,540,6,0,0,32.7,7,21,13,0,1,1
17,Pasveer,Ajax,Goalkeeper,540,6,0,0,32.7,25,13,6,0,2,2
18,Grbić,LOSC,Goalkeeper,540,6,0,0,31.9,25,13,4,0,3,1
19,Diogo Costa,Porto,Goalkeeper,540,6,0,0,31.7,11,18,11,0,2,2
20,Ter Stegen,Barcelona,Goalkeeper,540,6,0,0,29,16,16,9,0,3,2
21,Casteels,Wolfsburg,Goalkeeper,450,5,0,0,30.8,11,18,8,0,1,2
22,Ersin Destanoğlu,Beşiktaş,Goalkeeper,450,5,0,0,29.3,8,20,17,0,0,0
23,Donnarumma,Paris,Goalkeeper,450,5,0,0,27.5,11,18,6,1,2,9
24,Gulácsi,Leipzig,Goalkeeper,450,5,0,0,27.2,32,11,14,0,0,0
25,Bushchan,Dynamo Kyiv,Goalkeeper,450,5,0,0,25.6,25,13,11,0,0,4
26,Athanasiadis,Sheriff,Goalkeeper,450,5,0,0,22.7,4,29,8,0,1,2
27,Kritsyuk,Zenit,Goalkeeper,360,4,0,0,19.5,29,12,6,0,1,10
28,Dahlin,Malmö,Goalkeeper,315,4,0,0,14.2,9,19,8,1,0,3
29,Faivre,Young Boys,Goalkeeper,270,3,0,0,20.5,29,12,6,0,0,1
30,Tătăruşanu,Milan,Goalkeeper,270,3,0,0,18.6,36,8,2,0,1,2
31,Maignan,Milan,Goalkeeper,270,3,0,0,18.3,19,14,7,1,0,1
32,Trubin,Shakhtar Donetsk,Goalkeeper,270,3,0,0,15.5,11,18,9,0,0,0
33,Navas,Paris,Goalkeeper,270,3,0,0,13.7,32,11,5,0,0,3
34,Von Ballmoos,Young Boys,Goalkeeper,270,3,0,0,12.2,34,9,6,0,0,1
35,Pyatov,Shakhtar Donetsk,Goalkeeper,266,3,0,0,14.2,38,5,2,0,2,4
36,Diawara,Malmö,Goalkeeper,225,3,0,0,11.1,25,13,6,0,0,1
37,Leo Jardim,LOSC,Goalkeeper,180,2,0,0,11.1,41,4,4,0,0,0
38,M. Kerzhakov,Zenit,Goalkeeper,180,2,0,0,10.6,38,5,4,0,0,0
39,Onana,Ajax,Goalkeeper,180,2,0,0,8.4,50,2,2,0,0,0
40,Ulreich,Bayern,Goalkeeper,90,1,0,0,6.2,41,4,1,0,0,2
41,Martínez,Leipzig,Goalkeeper,90,1,0,0,6,46,3,0,0,1,0
42,Pervan,Wolfsburg,Goalkeeper,90,1,0,0,5.7,38,5,2,0,0,0
43,Kepa,Chelsea,Goalkeeper,90,1,0,0,5.6,41,4,3,0,0,0
44,João Virginia,Sporting CP,Goalkeeper,90,1,0,0,5.4,46,3,4,0,0,0
45,Günok,Beşiktaş,Goalkeeper,90,1,0,0,4.8,41,4,2,0,0,0
46,Celeadnic,Sheriff,Goalkeeper,90,1,0,0,4.7,37,6,3,0,0,1
47,Boyko,Dynamo Kyiv,Goalkeeper,90,1,0,0,4.5,41,4,0,0,1,2
48,Perin,Juventus,Goalkeeper,90,1,0,0,4.3,50,2,0,0,1,0
49,Steffen,Man. City,Goalkeeper,90,1,0,0,4,46,3,2,0,0,1
50,Henderson,Man. United,Goalkeeper,68,1,0,0,4.4,46,3,1,0,0,1
51,Carson,Man. City,Goalkeeper,17,1,0,0,1.1,52,1,0,0,1,0
52,Shevchenko,Shakhtar Donetsk,Goalkeeper,4,1,0,0,0.5,52,1,1,0,0,0

In [66]:
pd.merge(stats,attempt,how = 'inner')

,player_name,club,position,minutes_played,match_played,goals,assists,distance_covered,serial,total_attempts,on_target,off_target,blocked
0,Vinícius Júnior,Real Madrid,Forward,1199,13,4,6,133.0,8,27,8,10,9
1,Benzema,Real Madrid,Forward,1106,12,15,1,121.5,1,45,23,13,9
2,Modrić,Real Madrid,Midfielder,1077,13,0,4,124.5,40,14,5,3,6
3,Éder Militão,Real Madrid,Defender,1076,12,0,0,110.4,98,9,4,5,0
4,Alaba,Real Madrid,Defender,1040,12,1,0,112.3,179,5,1,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
538,Izquierdo,Club Brugge,Forward,8,1,0,0,1.3,440,1,0,0,1
539,Dina Ebimbe,Paris,Midfielder,7,1,0,0,1.2,440,1,0,0,1
540,Šimić,Salzburg,Forward,4,1,0,0,1.3,440,1,0,0,1
541,Maier,Young Boys,Midfielder,3,1,0,0,1.3,440,1,0,1,0
542,Kuznetsov,Zenit,Forward,3,1,0,0,0.9,440,1,0,0,1

In [67]:
pd.merge(stats,distri,how='inner')

,player_name,club,position,minutes_played,match_played,goals,assists,distance_covered,serial,pass_accuracy,pass_attempted,pass_completed,cross_accuracy,cross_attempted,cross_complted,freekicks_taken
0,Courtois,Real Madrid,Goalkeeper,1230,13,0,0,64.2,447,76.7,483,365,0,0,0,27
1,Vinícius Júnior,Real Madrid,Forward,1199,13,4,6,133.0,304,83.1,451,377,31,19,6,0
2,Benzema,Real Madrid,Forward,1106,12,15,1,121.5,304,83.1,523,433,20,10,2,4
3,Modrić,Real Madrid,Midfielder,1077,13,0,4,124.5,106,89.8,799,723,25,12,3,26
4,Éder Militão,Real Madrid,Defender,1076,12,0,0,110.4,158,87.5,643,563,0,2,0,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
602,Günok,Beşiktaş,Goalkeeper,90,1,0,0,4.8,555,66.0,38,25,0,0,0,1
603,Celeadnic,Sheriff,Goalkeeper,90,1,0,0,4.7,361,81.0,31,25,0,0,0,2
604,Boyko,Dynamo Kyiv,Goalkeeper,90,1,0,0,4.5,484,74.0,31,23,0,0,0,2
605,Perin,Juventus,Goalkeeper,90,1,0,0,4.3,405,79.0,19,15,0,0,0,0
606,Steffen,Man. City,Goalkeeper,90,1,0,0,4,48,92.0,25,23,0,0,0,3

In [68]:
pd.merge(stats,disc,how='inner')

,player_name,club,position,minutes_played,match_played,goals,assists,distance_covered,serial,fouls_committed,fouls_suffered,red,yellow
0,Vinícius Júnior,Real Madrid,Forward,1199,13,4,6,133.0,26,13,24,1,0
1,Benzema,Real Madrid,Forward,1106,12,15,1,121.5,417,2,4,1,0
2,Modrić,Real Madrid,Midfielder,1077,13,0,4,124.5,326,3,8,1,0
3,Éder Militão,Real Madrid,Defender,1076,12,0,0,110.4,6,17,16,4,0
4,Alaba,Real Madrid,Defender,1040,12,1,0,112.3,71,9,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,Iborra,Villarreal,Midfielder,10,1,0,0,1.8,491,1,0,0,0
578,Zhegrova,LOSC,Midfielder,9,1,0,0,1.9,491,1,0,0,0
579,Chiellini,Juventus,Defender,7,1,0,0,1.3,491,1,0,0,0
580,Delap,Man. City,Forward,6,1,0,0,1.2,417,2,0,0,0
581,Dentinho,Shakhtar Donetsk,Midfielder,4,1,0,0,1,491,1,0,1,0

In [70]:
pd.merge(stats,defend,how='inner')

,player_name,club,position,minutes_played,match_played,goals,assists,distance_covered,serial,balls_recoverd,tackles,t_won,t_lost,clearance_attempted
0,Vinícius Júnior,Real Madrid,Forward,1199,13,4,6,133.0,121,29,11,3,8,0
1,Benzema,Real Madrid,Forward,1106,12,15,1,121.5,428,6,1,1,0,10
2,Modrić,Real Madrid,Midfielder,1077,13,0,4,124.5,54,39,9,3,6,4
3,Éder Militão,Real Madrid,Defender,1076,12,0,0,110.4,1,76,19,6,13,32
4,Alaba,Real Madrid,Defender,1040,12,1,0,112.3,22,49,18,12,6,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
620,Guindo,Salzburg,Defender,4,1,0,0,1.2,578,1,1,1,0,0
621,Maier,Young Boys,Midfielder,3,1,0,0,1.3,578,1,0,0,0,0
622,Kuznetsov,Zenit,Forward,3,1,0,0,0.9,578,1,0,0,0,0
623,Miretti,Juventus,Midfielder,1,1,0,0,0.8,578,1,0,0,0,0
624,Zesiger,Young Boys,Defender,1,1,0,0,-,578,1,0,0,0,0

In [75]:
attack.player_name.nunique()

176

In [76]:
defend.player_name.nunique()

617

In [77]:
attempt.player_name.nunique()

540

In [79]:
goal.player_name.nunique()

183

In [80]:
stats.player_name.nunique()

731

In [81]:
goalkeep.player_name.nunique()

53

In [82]:
disc.player_name.nunique()

574

In [83]:
distri.player_name.nunique()

595

In [111]:
m = pd.merge(stats,goalkeep,how = 'outer').drop_duplicates(subset = 'player_name',keep='first').reset_index()

In [112]:
m

,index,player_name,club,position,minutes_played,match_played,goals,assists,distance_covered,serial,saved,conceded,saved_penalties,cleansheets,punches made
0,0,Courtois,Real Madrid,Goalkeeper,1230,13,0,0,64.2,1.0,61.0,14.0,1.0,5.0,4.0
1,1,Vinícius Júnior,Real Madrid,Forward,1199,13,4,6,133.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Benzema,Real Madrid,Forward,1106,12,15,1,121.5,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Modrić,Real Madrid,Midfielder,1077,13,0,4,124.5,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Éder Militão,Real Madrid,Defender,1076,12,0,0,110.4,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,742,Gil Dias,Benfica,Midfielder,1,1,0,0,0.7,NaN,NaN,NaN,NaN,NaN,NaN
727,743,Rodrigo Ribeiro,Sporting CP,Forward,1,1,0,0,0.7,NaN,NaN,NaN,NaN,NaN,NaN
728,744,Cojocari,Sheriff,Defender,1,1,0,0,0.5,NaN,NaN,NaN,NaN,NaN,NaN
729,745,Maouassa,Club Brugge,Defender,1,1,0,0,0.2,NaN,NaN,NaN,NaN,NaN,NaN
730,746,Zesiger,Young Boys,Defender,1,1,0,0,-,NaN,NaN,NaN,NaN,NaN,NaN

In [135]:
pd.merge(m,attack,on= ['player_name','club','position'],how = 'left')

,index,player_name,club,position,minutes_played,match_played_x,goals,assists_x,distance_covered,serial_x,saved,conceded,saved_penalties,cleansheets,punches made,serial_y,assists_y,corner_taken,offsides,dribbles,match_played_y
0,0,Courtois,Real Madrid,Goalkeeper,1230,13,0,0,64.2,1.0,61.0,14.0,1.0,5.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Vinícius Júnior,Real Madrid,Forward,1199,13,4,6,133.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,6.0,3.0,4.0,83.0,13.0
2,2,Benzema,Real Madrid,Forward,1106,12,15,1,121.5,NaN,NaN,NaN,NaN,NaN,NaN,64.0,1.0,2.0,9.0,18.0,12.0
3,3,Modrić,Real Madrid,Midfielder,1077,13,0,4,124.5,NaN,NaN,NaN,NaN,NaN,NaN,5.0,4.0,10.0,0.0,8.0,13.0
4,4,Éder Militão,Real Madrid,Defender,1076,12,0,0,110.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,742,Gil Dias,Benfica,Midfielder,1,1,0,0,0.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
727,743,Rodrigo Ribeiro,Sporting CP,Forward,1,1,0,0,0.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
728,744,Cojocari,Sheriff,Defender,1,1,0,0,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
729,745,Maouassa,Club Brugge,Defender,1,1,0,0,0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
730,746,Zesiger,Young Boys,Defender,1,1,0,0,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [106]:
goal.head()

,serial,player_name,club,position,goals,right_foot,left_foot,headers,others,inside_area,outside_areas,penalties,match_played
0,1,Benzema,Real Madrid,Forward,15,11,1,3,0,13,2,3,12
1,2,Lewandowski,Bayern,Forward,13,8,3,1,1,13,0,3,10
2,3,Haller,Ajax,Forward,11,3,4,3,1,11,0,1,8
3,4,Salah,Liverpool,Forward,8,0,8,0,0,7,1,1,13
4,5,Nkunku,Leipzig,Midfielder,7,3,1,3,0,7,0,0,6

In [124]:
stats[stats.duplicated('player_name')]

,player_name,club,position,minutes_played,match_played,goals,assists,distance_covered
71,Mendy,Chelsea,Goalkeeper,840,9,0,0,57.4
130,Martínez,Inter,Forward,587,8,1,0,67.4
333,Danilo,Paris,Midfielder,362,7,0,0,40.6
348,João Mário,Porto,Forward,351,4,0,0,39.3
349,Fernando,Shakhtar Donetsk,Midfielder,350,5,2,0,34.8
354,Camara,Young Boys,Defender,347,4,0,0,30.5
467,Herrera,Atlético,Midfielder,226,4,0,0,30.1
514,Onana,Ajax,Goalkeeper,180,2,0,0,8.4
543,Karavaev,Dynamo Kyiv,Defender,154,6,0,0,21.6
580,Correa,Inter,Forward,106,5,0,0,14.8
588,Sarr,Chelsea,Defender,100,2,0,0,11.9
609,Martínez,Leipzig,Goalkeeper,90,1,0,0,6
617,Steffen,Man. City,Goalkeeper,90,1,0,0,4
645,Diallo,Man. United,Midfielder,68,1,0,0,8.3
646,Henderson,Man. United,Goalkeeper,68,1,0,0,4.4
699,Peña,Villarreal,Defender,18,2,0,0,3.3

In [128]:
pd.merge([attack,goal,defend,goalkeep,stats],on='player_name',how='right')

TypeError: merge() missing 1 required positional argument: 'right'

In [130]:
attack.head()

,serial,player_name,club,position,assists,corner_taken,offsides,dribbles,match_played
0,1,Bruno Fernandes,Man. United,Midfielder,7,10,2,7,7
1,2,Vinícius Júnior,Real Madrid,Forward,6,3,4,83,13
2,2,Sané,Bayern,Midfielder,6,3,3,32,10
3,4,Antony,Ajax,Forward,5,3,4,28,7
4,5,Alexander-Arnold,Liverpool,Defender,4,36,0,9,9

In [20]:
stats.drop_duplicates(subset='player_name',keep ='first',inplace =True)

In [24]:
stats.reset_index(drop =True,inplace =True)

In [25]:
stats

,player_name,club,position,minutes_played,match_played,goals,assists,distance_covered
0,Courtois,Real Madrid,Goalkeeper,1230,13,0,0,64.2
1,Vinícius Júnior,Real Madrid,Forward,1199,13,4,6,133.0
2,Benzema,Real Madrid,Forward,1106,12,15,1,121.5
3,Modrić,Real Madrid,Midfielder,1077,13,0,4,124.5
4,Éder Militão,Real Madrid,Defender,1076,12,0,0,110.4
...,...,...,...,...,...,...,...,...
726,Gil Dias,Benfica,Midfielder,1,1,0,0,0.7
727,Rodrigo Ribeiro,Sporting CP,Forward,1,1,0,0,0.7
728,Cojocari,Sheriff,Defender,1,1,0,0,0.5
729,Maouassa,Club Brugge,Defender,1,1,0,0,0.2
730,Zesiger,Young Boys,Defender,1,1,0,0,-

In [26]:
attempt.drop_duplicates(subset='player_name',keep ='first',inplace =True)

In [28]:
attempt.reset_index(drop =True,inplace =True)

In [29]:
disc.drop_duplicates(subset='player_name',keep ='first',inplace =True)

In [30]:
disc.reset_index(drop =True,inplace =True)

In [31]:
distri.drop_duplicates(subset='player_name',keep ='first',inplace =True)

In [32]:
distri.reset_index(drop =True,inplace =True)

In [33]:
defend.drop_duplicates(subset='player_name',keep ='first',inplace =True)
defend.reset_index(drop =True,inplace =True)

In [34]:
goalkeep.drop_duplicates(subset='player_name',keep ='first',inplace =True)
goalkeep.reset_index(drop =True,inplace =True)

In [35]:
goal.drop_duplicates(subset='player_name',keep ='first',inplace =True)
goal.reset_index(drop =True,inplace =True)

In [36]:
stats.drop_duplicates(subset='player_name',keep ='first',inplace =True)
stats.reset_index(drop =True,inplace =True)

In [37]:
attack.head()

,serial,player_name,club,position,assists,corner_taken,offsides,dribbles,match_played
0,1,Bruno Fernandes,Man. United,Midfielder,7,10,2,7,7
1,2,Vinícius Júnior,Real Madrid,Forward,6,3,4,83,13
2,2,Sané,Bayern,Midfielder,6,3,3,32,10
3,4,Antony,Ajax,Forward,5,3,4,28,7
4,5,Alexander-Arnold,Liverpool,Defender,4,36,0,9,9

In [42]:
stats.head()

,player_name,club,position,minutes_played,match_played,goals,assists,distance_covered
0,Courtois,Real Madrid,Goalkeeper,1230,13,0,0,64.2
1,Vinícius Júnior,Real Madrid,Forward,1199,13,4,6,133.0
2,Benzema,Real Madrid,Forward,1106,12,15,1,121.5
3,Modrić,Real Madrid,Midfielder,1077,13,0,4,124.5
4,Éder Militão,Real Madrid,Defender,1076,12,0,0,110.4

In [52]:
m1 = pd.merge(stats,attack,on=['player_name','club','position','match_played','assists'],how = 'left')

In [53]:
m1

,player_name,club,position,minutes_played,match_played,goals,assists,distance_covered,serial,corner_taken,offsides,dribbles
0,Courtois,Real Madrid,Goalkeeper,1230,13,0,0,64.2,NaN,NaN,NaN,NaN
1,Vinícius Júnior,Real Madrid,Forward,1199,13,4,6,133.0,2.0,3.0,4.0,83.0
2,Benzema,Real Madrid,Forward,1106,12,15,1,121.5,64.0,2.0,9.0,18.0
3,Modrić,Real Madrid,Midfielder,1077,13,0,4,124.5,5.0,10.0,0.0,8.0
4,Éder Militão,Real Madrid,Defender,1076,12,0,0,110.4,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
726,Gil Dias,Benfica,Midfielder,1,1,0,0,0.7,NaN,NaN,NaN,NaN
727,Rodrigo Ribeiro,Sporting CP,Forward,1,1,0,0,0.7,NaN,NaN,NaN,NaN
728,Cojocari,Sheriff,Defender,1,1,0,0,0.5,NaN,NaN,NaN,NaN
729,Maouassa,Club Brugge,Defender,1,1,0,0,0.2,NaN,NaN,NaN,NaN
730,Zesiger,Young Boys,Defender,1,1,0,0,-,NaN,NaN,NaN,NaN

In [47]:
goalkeep.head()

,serial,player_name,club,position,saved,conceded,saved_penalties,cleansheets,punches made,match_played
0,1,Courtois,Real Madrid,Goalkeeper,61,14,1,5,4,13
1,2,Rulli,Villarreal,Goalkeeper,41,16,0,3,12,12
2,3,Vlachodimos,Benfica,Goalkeeper,38,17,1,5,5,10
3,4,Athanasiadis,Sheriff,Goalkeeper,29,8,0,1,2,5
4,5,Mignolet,Club Brugge,Goalkeeper,28,20,0,0,1,6

In [56]:
m2 = pd.merge(m1,goalkeep,on = ['player_name','club','position','match_played'],how = 'left').drop(['serial_x','serial_y'],axis = 1)

In [57]:
m2

,player_name,club,position,minutes_played,match_played,goals,assists,distance_covered,corner_taken,offsides,dribbles,saved,conceded,saved_penalties,cleansheets,punches made
0,Courtois,Real Madrid,Goalkeeper,1230,13,0,0,64.2,NaN,NaN,NaN,61.0,14.0,1.0,5.0,4.0
1,Vinícius Júnior,Real Madrid,Forward,1199,13,4,6,133.0,3.0,4.0,83.0,NaN,NaN,NaN,NaN,NaN
2,Benzema,Real Madrid,Forward,1106,12,15,1,121.5,2.0,9.0,18.0,NaN,NaN,NaN,NaN,NaN
3,Modrić,Real Madrid,Midfielder,1077,13,0,4,124.5,10.0,0.0,8.0,NaN,NaN,NaN,NaN,NaN
4,Éder Militão,Real Madrid,Defender,1076,12,0,0,110.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,Gil Dias,Benfica,Midfielder,1,1,0,0,0.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
727,Rodrigo Ribeiro,Sporting CP,Forward,1,1,0,0,0.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
728,Cojocari,Sheriff,Defender,1,1,0,0,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
729,Maouassa,Club Brugge,Defender,1,1,0,0,0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
730,Zesiger,Young Boys,Defender,1,1,0,0,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
goal.head()

,serial,player_name,club,position,goals,right_foot,left_foot,headers,others,inside_area,outside_areas,penalties,match_played
0,1,Benzema,Real Madrid,Forward,15,11,1,3,0,13,2,3,12
1,2,Lewandowski,Bayern,Forward,13,8,3,1,1,13,0,3,10
2,3,Haller,Ajax,Forward,11,3,4,3,1,11,0,1,8
3,4,Salah,Liverpool,Forward,8,0,8,0,0,7,1,1,13
4,5,Nkunku,Leipzig,Midfielder,7,3,1,3,0,7,0,0,6

In [66]:
m3 =  pd.merge(m2,goal,on = ['player_name','club','position','match_played','goals'],how = 'left').drop('serial',axis =1)

In [67]:
m3

,player_name,club,position,minutes_played,match_played,goals,assists,distance_covered,corner_taken,offsides,dribbles,saved,conceded,saved_penalties,cleansheets,punches made,right_foot,left_foot,headers,others,inside_area,outside_areas,penalties
0,Courtois,Real Madrid,Goalkeeper,1230,13,0,0,64.2,NaN,NaN,NaN,61.0,14.0,1.0,5.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Vinícius Júnior,Real Madrid,Forward,1199,13,4,6,133.0,3.0,4.0,83.0,NaN,NaN,NaN,NaN,NaN,3.0,1.0,0.0,0.0,4.0,0.0,0.0
2,Benzema,Real Madrid,Forward,1106,12,15,1,121.5,2.0,9.0,18.0,NaN,NaN,NaN,NaN,NaN,11.0,1.0,3.0,0.0,13.0,2.0,3.0
3,Modrić,Real Madrid,Midfielder,1077,13,0,4,124.5,10.0,0.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Éder Militão,Real Madrid,Defender,1076,12,0,0,110.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,Gil Dias,Benfica,Midfielder,1,1,0,0,0.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
727,Rodrigo Ribeiro,Sporting CP,Forward,1,1,0,0,0.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
728,Cojocari,Sheriff,Defender,1,1,0,0,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
729,Maouassa,Club Brugge,Defender,1,1,0,0,0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
730,Zesiger,Young Boys,Defender,1,1,0,0,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [71]:
attempt.drop('serial',axis=1,inplace=True)

In [73]:
m4 = pd.merge(m3,attempt,on = ['player_name','club','position','match_played'],how = 'left')

In [74]:
m4

,player_name,club,position,minutes_played,match_played,goals,assists,distance_covered,corner_taken,offsides,dribbles,saved,conceded,saved_penalties,cleansheets,punches made,right_foot,left_foot,headers,others,inside_area,outside_areas,penalties,total_attempts,on_target,off_target,blocked
0,Courtois,Real Madrid,Goalkeeper,1230,13,0,0,64.2,NaN,NaN,NaN,61.0,14.0,1.0,5.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Vinícius Júnior,Real Madrid,Forward,1199,13,4,6,133.0,3.0,4.0,83.0,NaN,NaN,NaN,NaN,NaN,3.0,1.0,0.0,0.0,4.0,0.0,0.0,27.0,8.0,10.0,9.0
2,Benzema,Real Madrid,Forward,1106,12,15,1,121.5,2.0,9.0,18.0,NaN,NaN,NaN,NaN,NaN,11.0,1.0,3.0,0.0,13.0,2.0,3.0,45.0,23.0,13.0,9.0
3,Modrić,Real Madrid,Midfielder,1077,13,0,4,124.5,10.0,0.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0,5.0,3.0,6.0
4,Éder Militão,Real Madrid,Defender,1076,12,0,0,110.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,4.0,5.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,Gil Dias,Benfica,Midfielder,1,1,0,0,0.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
727,Rodrigo Ribeiro,Sporting CP,Forward,1,1,0,0,0.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
728,Cojocari,Sheriff,Defender,1,1,0,0,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
729,Maouassa,Club Brugge,Defender,1,1,0,0,0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
730,Zesiger,Young Boys,Defender,1,1,0,0,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [78]:
defend.drop('serial',axis= 1,inplace=True)

In [83]:
 m5 = pd.merge(m4,defend,on = ['player_name','club','position','match_played'],how = 'left')

In [84]:
m5

,player_name,club,position,minutes_played,match_played,goals,assists,distance_covered,corner_taken,offsides,dribbles,saved,conceded,saved_penalties,cleansheets,punches made,right_foot,left_foot,headers,others,inside_area,outside_areas,penalties,total_attempts,on_target,off_target,blocked,balls_recoverd,tackles,t_won,t_lost,clearance_attempted
0,Courtois,Real Madrid,Goalkeeper,1230,13,0,0,64.2,NaN,NaN,NaN,61.0,14.0,1.0,5.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Vinícius Júnior,Real Madrid,Forward,1199,13,4,6,133.0,3.0,4.0,83.0,NaN,NaN,NaN,NaN,NaN,3.0,1.0,0.0,0.0,4.0,0.0,0.0,27.0,8.0,10.0,9.0,29.0,11.0,3.0,8.0,0.0
2,Benzema,Real Madrid,Forward,1106,12,15,1,121.5,2.0,9.0,18.0,NaN,NaN,NaN,NaN,NaN,11.0,1.0,3.0,0.0,13.0,2.0,3.0,45.0,23.0,13.0,9.0,6.0,1.0,1.0,0.0,10.0
3,Modrić,Real Madrid,Midfielder,1077,13,0,4,124.5,10.0,0.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0,5.0,3.0,6.0,39.0,9.0,3.0,6.0,4.0
4,Éder Militão,Real Madrid,Defender,1076,12,0,0,110.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,4.0,5.0,0.0,76.0,19.0,6.0,13.0,32.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,Gil Dias,Benfica,Midfielder,1,1,0,0,0.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
727,Rodrigo Ribeiro,Sporting CP,Forward,1,1,0,0,0.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
728,Cojocari,Sheriff,Defender,1,1,0,0,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
729,Maouassa,Club Brugge,Defender,1,1,0,0,0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
730,Zesiger,Young Boys,Defender,1,1,0,0,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0

In [87]:
disc.drop('serial',axis= 1,inplace=True)

In [88]:
disc

,player_name,club,position,fouls_committed,fouls_suffered,red,yellow,minutes_played,match_played
0,João Palhinha,Sporting CP,Midfielder,23,17,2,0,534,6
1,Capoue,Villarreal,Midfielder,19,17,3,1,1046,12
2,Rodri,Man. City,Midfielder,19,4,2,0,842,10
3,Seiwald,Salzburg,Midfielder,19,3,2,0,649,8
4,Balanta,Club Brugge,Midfielder,18,3,4,0,407,5
...,...,...,...,...,...,...,...,...,...
569,Eric Ramirez,Dynamo Kyiv,Forward,1,0,0,0,16,2
570,Bradarić,LOSC,Defender,1,0,0,0,13,1
571,Iborra,Villarreal,Midfielder,1,0,0,0,10,1
572,Zhegrova,LOSC,Midfielder,1,0,0,0,9,1
573,Chiellini,Juventus,Defender,1,0,0,0,7,1

In [94]:
 m6 = pd.merge(m5,disc,on = ['player_name','club','position','match_played','minutes_played'],how = 'left')

In [93]:
distri.drop('serial',axis= 1,inplace=True)

In [97]:
m7 = pd.merge(m6,distri,on = ['player_name','club','position','match_played'],how = 'left')

In [98]:
m7.columns

Index(['player_name', 'club', 'position', 'minutes_played', 'match_played',
       'goals', 'assists', 'distance_covered', 'corner_taken', 'offsides',
       'dribbles', 'saved', 'conceded', 'saved_penalties', 'cleansheets',
       'punches made', 'right_foot', 'left_foot', 'headers', 'others',
       'inside_area', 'outside_areas', 'penalties', 'total_attempts',
       'on_target', 'off_target', 'blocked', 'balls_recoverd', 'tackles',
       't_won', 't_lost', 'clearance_attempted', 'fouls_committed',
       'fouls_suffered', 'red', 'yellow', 'pass_accuracy', 'pass_attempted',
       'pass_completed', 'cross_accuracy', 'cross_attempted', 'cross_complted',
       'freekicks_taken'],
      dtype='object')

In [117]:
m8 = m7.replace('[-]','0',regex=True)

In [122]:
m8.iloc[m8.distance_covered.astype(float).sort_values(ascending=False).index]

,player_name,club,position,minutes_played,match_played,goals,assists,distance_covered,corner_taken,offsides,dribbles,saved,conceded,saved_penalties,cleansheets,punches made,right_foot,left_foot,headers,others,inside_area,outside_areas,penalties,total_attempts,on_target,off_target,blocked,balls_recoverd,tackles,t_won,t_lost,clearance_attempted,fouls_committed,fouls_suffered,red,yellow,pass_accuracy,pass_attempted,pass_completed,cross_accuracy,cross_attempted,cross_complted,freekicks_taken
1,Vinícius Júnior,Real Madrid,Forward,1199,13,4,6,133.0,3.0,4.0,83.0,NaN,NaN,NaN,NaN,NaN,3.0,1.0,0.0,0.0,4.0,0.0,0.0,27.0,8.0,10.0,9.0,29.0,11.0,3.0,8.0,0.0,13.0,24.0,1.0,0.0,83.1,451.0,377.0,31.0,19.0,6.0,0.0
55,Parejo,Villarreal,Midfielder,1055,12,1,3,130.9,36.0,0.0,4.0,NaN,NaN,NaN,NaN,NaN,0.0,1.0,0.0,0.0,1.0,0.0,0.0,5.0,1.0,4.0,0.0,48.0,17.0,8.0,9.0,5.0,4.0,17.0,2.0,0.0,84.3,657.0,560.0,56.0,37.0,21.0,52.0
56,Capoue,Villarreal,Midfielder,1046,12,2,4,130.9,0.0,0.0,17.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,0.0,2.0,0.0,0.0,9.0,3.0,4.0,2.0,62.0,11.0,1.0,10.0,29.0,19.0,17.0,3.0,1.0,87.2,491.0,438.0,50.0,2.0,1.0,4.0
3,Modrić,Real Madrid,Midfielder,1077,13,0,4,124.5,10.0,0.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0,5.0,3.0,6.0,39.0,9.0,3.0,6.0,4.0,3.0,8.0,1.0,0.0,89.8,799.0,723.0,25.0,12.0,3.0,26.0
53,Pau Torres,Villarreal,Defender,1080,12,1,0,124.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,1.0,0.0,0.0,4.0,1.0,3.0,0.0,49.0,7.0,3.0,4.0,62.0,3.0,2.0,1.0,0.0,88.0,506.0,457.0,0.0,0.0,0.0,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52,Bradley,Liverpool,Midfielder,1,1,0,0,0.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,Woltman,Liverpool,Midfielder,1,1,0,0,0.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
729,Maouassa,Club Brugge,Defender,1,1,0,0,0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
709,Sulejmani,Young Boys,Midfielder,7,1,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
730,Zesiger,Young Boys,Defender,1,1,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [137]:
m8.sort_values(by=['goals','match_played','assists'],ascending=[False,True,False]).head(10).dropna(axis=1)

,player_name,club,position,minutes_played,match_played,goals,assists,distance_covered,right_foot,left_foot,headers,others,inside_area,outside_areas,penalties,total_attempts,on_target,off_target,blocked,balls_recoverd,tackles,t_won,t_lost,clearance_attempted,fouls_committed,fouls_suffered,red,yellow,pass_accuracy,pass_attempted,pass_completed,cross_accuracy,cross_attempted,cross_complted,freekicks_taken
2,Benzema,Real Madrid,Forward,1106,12,15,1,121.5,11.0,1.0,3.0,0.0,13.0,2.0,3.0,45.0,23.0,13.0,9.0,6.0,1.0,1.0,0.0,10.0,2.0,4.0,1.0,0.0,83.1,523.0,433.0,20.0,10.0,2.0,4.0
66,Lewandowski,Bayern,Forward,876,10,13,3,99.7,8.0,3.0,1.0,1.0,13.0,0.0,3.0,31.0,19.0,8.0,4.0,7.0,4.0,0.0,4.0,0.0,11.0,13.0,1.0,0.0,79.1,206.0,163.0,10.0,10.0,1.0,1.0
101,Haller,Ajax,Forward,668,8,11,1,82.2,3.0,4.0,3.0,1.0,11.0,0.0,1.0,24.0,15.0,8.0,1.0,10.0,8.0,2.0,6.0,5.0,17.0,11.0,1.0,0.0,80.8,162.0,134.0,0.0,0.0,0.0,0.0
26,Salah,Liverpool,Forward,1008,13,8,2,112.0,0.0,8.0,0.0,0.0,7.0,1.0,1.0,42.0,22.0,11.0,9.0,12.0,0.0,0.0,0.0,0.0,4.0,12.0,0.0,0.0,81.2,426.0,346.0,9.0,11.0,1.0,1.0
182,Nkunku,Leipzig,Midfielder,531,6,7,0,62.8,3.0,1.0,3.0,0.0,7.0,0.0,0.0,17.0,11.0,4.0,2.0,15.0,4.0,1.0,3.0,2.0,10.0,8.0,0.0,0.0,86.3,193.0,167.0,20.0,15.0,3.0,8.0
59,Mahrez,Man. City,Midfielder,986,12,7,2,120.1,1.0,4.0,2.0,0.0,7.0,0.0,2.0,37.0,18.0,8.0,11.0,20.0,6.0,1.0,5.0,3.0,6.0,20.0,1.0,0.0,84.9,482.0,414.0,24.0,49.0,12.0,11.0
125,Ronaldo,Man. United,Forward,611,7,6,0,59.2,5.0,0.0,1.0,0.0,4.0,2.0,0.0,22.0,12.0,8.0,2.0,5.0,3.0,1.0,2.0,6.0,4.0,11.0,1.0,0.0,87.2,204.0,179.0,60.0,5.0,3.0,4.0
98,Mbappé,Paris,Forward,673,8,6,4,65.2,6.0,0.0,0.0,0.0,6.0,0.0,0.0,27.0,16.0,6.0,5.0,10.0,1.0,0.0,1.0,2.0,3.0,11.0,1.0,0.0,85.4,257.0,220.0,13.0,15.0,2.0,0.0
75,Sané,Bayern,Midfielder,798,10,6,6,94,1.0,5.0,0.0,0.0,3.0,3.0,0.0,33.0,13.0,12.0,8.0,23.0,1.0,0.0,1.0,0.0,2.0,5.0,0.0,0.0,86.8,398.0,346.0,26.0,19.0,5.0,8.0
123,Núñez,Benfica,Forward,613,10,6,0,72.4,5.0,0.0,1.0,0.0,6.0,0.0,1.0,15.0,8.0,7.0,0.0,10.0,4.0,2.0,2.0,7.0,6.0,7.0,1.0,0.0,56.4,117.0,67.0,22.0,18.0,4.0,2.0

In [136]:
m8.sort_values(by = ['saved','conceded','saved_penalties','cleansheets','punches made'],ascending = [False,True,True,False,False]).head(15).dropna(axis =1)

,player_name,club,position,minutes_played,match_played,goals,assists,distance_covered,saved,conceded,saved_penalties,cleansheets,punches made,pass_accuracy,pass_attempted,pass_completed,cross_accuracy,cross_attempted,cross_complted,freekicks_taken
0,Courtois,Real Madrid,Goalkeeper,1230,13,0,0,64.2,61.0,14.0,1.0,5.0,4.0,76.7,483.0,365.0,0.0,0.0,0.0,27.0
54,Rulli,Villarreal,Goalkeeper,1080,12,0,0,61.2,41.0,16.0,0.0,3.0,12.0,68.2,489.0,332.0,0.0,0.0,0.0,53.0
62,Vlachodimos,Benfica,Goalkeeper,900,10,0,0,55.4,38.0,17.0,1.0,5.0,5.0,73.8,345.0,247.0,0.0,0.0,0.0,52.0
259,Athanasiadis,Sheriff,Goalkeeper,450,5,0,0,22.7,29.0,8.0,0.0,1.0,2.0,69.2,154.0,106.0,0.0,0.0,0.0,10.0
166,Mignolet,Club Brugge,Goalkeeper,540,6,0,0,33.2,28.0,20.0,0.0,0.0,1.0,78.7,216.0,166.0,0.0,0.0,0.0,18.0
63,Oblak,Atlético,Goalkeeper,900,10,0,0,52.7,26.0,10.0,0.0,3.0,2.0,55.7,283.0,158.0,0.0,0.0,0.0,31.0
167,Musso,Atalanta,Goalkeeper,540,6,0,0,32.7,21.0,13.0,0.0,1.0,1.0,76.0,158.0,120.0,0.0,0.0,0.0,11.0
255,Ersin Destanoğlu,Beşiktaş,Goalkeeper,450,5,0,0,29.3,20.0,17.0,0.0,0.0,0.0,70.2,145.0,101.0,0.0,0.0,0.0,7.0
381,Dahlin,Malmö,Goalkeeper,315,4,0,0,14.2,19.0,8.0,1.0,0.0,3.0,53.0,98.0,52.0,0.0,0.0,0.0,13.0
120,De Gea,Man. United,Goalkeeper,630,7,0,0,26.4,19.0,9.0,0.0,1.0,0.0,74.6,164.0,121.0,0.0,0.0,0.0,9.0
256,Donnarumma,Paris,Goalkeeper,450,5,0,0,27.5,18.0,6.0,1.0,2.0,9.0,83.8,153.0,128.0,0.0,0.0,0.0,13.0
254,Casteels,Wolfsburg,Goalkeeper,450,5,0,0,30.8,18.0,8.0,0.0,1.0,2.0,71.4,182.0,129.0,0.0,0.0,0.0,10.0
423,Trubin,Shakhtar Donetsk,Goalkeeper,270,3,0,0,15.5,18.0,9.0,0.0,0.0,0.0,83.0,94.0,78.0,0.0,0.0,0.0,5.0
170,Diogo Costa,Porto,Goalkeeper,540,6,0,0,31.7,18.0,11.0,0.0,2.0,2.0,64.8,269.0,173.0,0.0,0.0,0.0,33.0
118,Adán,Sporting CP,Goalkeeper,630,7,0,0,36.3,17.0,13.0,0.0,2.0,8.0,70.2,233.0,166.0,0.0,0.0,0.0,34.0

In [128]:
m8

,player_name,club,position,minutes_played,match_played,goals,assists,distance_covered,corner_taken,offsides,dribbles,saved,conceded,saved_penalties,cleansheets,punches made,right_foot,left_foot,headers,others,inside_area,outside_areas,penalties,total_attempts,on_target,off_target,blocked,balls_recoverd,tackles,t_won,t_lost,clearance_attempted,fouls_committed,fouls_suffered,red,yellow,pass_accuracy,pass_attempted,pass_completed,cross_accuracy,cross_attempted,cross_complted,freekicks_taken
0,Courtois,Real Madrid,Goalkeeper,1230,13,0,0,64.2,NaN,NaN,NaN,61.0,14.0,1.0,5.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76.7,483.0,365.0,0.0,0.0,0.0,27.0
1,Vinícius Júnior,Real Madrid,Forward,1199,13,4,6,133.0,3.0,4.0,83.0,NaN,NaN,NaN,NaN,NaN,3.0,1.0,0.0,0.0,4.0,0.0,0.0,27.0,8.0,10.0,9.0,29.0,11.0,3.0,8.0,0.0,13.0,24.0,1.0,0.0,83.1,451.0,377.0,31.0,19.0,6.0,0.0
2,Benzema,Real Madrid,Forward,1106,12,15,1,121.5,2.0,9.0,18.0,NaN,NaN,NaN,NaN,NaN,11.0,1.0,3.0,0.0,13.0,2.0,3.0,45.0,23.0,13.0,9.0,6.0,1.0,1.0,0.0,10.0,2.0,4.0,1.0,0.0,83.1,523.0,433.0,20.0,10.0,2.0,4.0
3,Modrić,Real Madrid,Midfielder,1077,13,0,4,124.5,10.0,0.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0,5.0,3.0,6.0,39.0,9.0,3.0,6.0,4.0,3.0,8.0,1.0,0.0,89.8,799.0,723.0,25.0,12.0,3.0,26.0
4,Éder Militão,Real Madrid,Defender,1076,12,0,0,110.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,4.0,5.0,0.0,76.0,19.0,6.0,13.0,32.0,17.0,16.0,4.0,0.0,87.5,643.0,563.0,0.0,2.0,0.0,17.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,Gil Dias,Benfica,Midfielder,1,1,0,0,0.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
727,Rodrigo Ribeiro,Sporting CP,Forward,1,1,0,0,0.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
728,Cojocari,Sheriff,Defender,1,1,0,0,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
729,Maouassa,Club Brugge,Defender,1,1,0,0,0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
730,Zesiger,Young Boys,Defender,1,1,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [139]:
m8.sort_values(by = ['tackles','t_won','t_lost','fouls_committed','red','yellow'],ascending = [False,False,True,True,True,True]).head(15)

,player_name,club,position,minutes_played,match_played,goals,assists,distance_covered,corner_taken,offsides,dribbles,saved,conceded,saved_penalties,cleansheets,punches made,right_foot,left_foot,headers,others,inside_area,outside_areas,penalties,total_attempts,on_target,off_target,blocked,balls_recoverd,tackles,t_won,t_lost,clearance_attempted,fouls_committed,fouls_suffered,red,yellow,pass_accuracy,pass_attempted,pass_completed,cross_accuracy,cross_attempted,cross_complted,freekicks_taken
278,Verratti,Paris,Midfielder,431,5,0,0,55.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.0,35.0,18.0,17.0,4.0,5.0,10.0,2.0,0.0,93.0,436.0,403.0,0.0,2.0,0.0,14.0
7,Casemiro,Real Madrid,Midfielder,914,11,0,0,107.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,2.0,6.0,2.0,76.0,31.0,13.0,18.0,19.0,17.0,18.0,3.0,0.0,89.1,538.0,482.0,25.0,4.0,1.0,6.0
178,João Palhinha,Sporting CP,Midfielder,534,6,0,0,66.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,1.0,2.0,1.0,36.0,29.0,11.0,18.0,6.0,23.0,17.0,2.0,0.0,85.0,194.0,165.0,0.0,1.0,0.0,14.0
74,Otamendi,Benfica,Defender,810,9,0,0,91.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,1.0,3.0,0.0,63.0,28.0,17.0,11.0,48.0,17.0,11.0,2.0,0.0,84.3,380.0,328.0,0.0,1.0,0.0,14.0
213,Addo,Sheriff,Midfielder,491,6,0,0,59.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1.0,0.0,27.0,26.0,7.0,19.0,10.0,14.0,4.0,3.0,0.0,85.2,137.0,118.0,0.0,0.0,0.0,2.0
116,André,LOSC,Midfielder,630,7,0,0,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,1.0,1.0,3.0,49.0,24.0,12.0,12.0,11.0,9.0,10.0,3.0,0.0,82.0,352.0,289.0,0.0,4.0,0.0,7.0
73,Weigl,Benfica,Midfielder,810,9,0,0,112,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,0.0,1.0,35.0,23.0,12.0,11.0,12.0,10.0,5.0,2.0,0.0,89.1,351.0,316.0,0.0,3.0,0.0,8.0
27,Fabinho,Liverpool,Midfielder,849,13,1,0,105.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,1.0,0.0,0.0,5.0,1.0,2.0,2.0,74.0,23.0,9.0,14.0,8.0,14.0,11.0,1.0,0.0,90.3,595.0,549.0,0.0,2.0,0.0,9.0
224,Renan Lodi,Atlético,Defender,478,10,1,2,61.7,1.0,5.0,9.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,1.0,0.0,0.0,4.0,2.0,1.0,1.0,23.0,21.0,6.0,15.0,8.0,14.0,6.0,0.0,0.0,78.8,164.0,128.0,25.0,20.0,5.0,5.0
266,Souza,Beşiktaş,Midfielder,442,5,0,0,55.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,0.0,2.0,1.0,40.0,20.0,12.0,8.0,9.0,7.0,3.0,3.0,1.0,87.2,267.0,237.0,0.0,1.0,0.0,13.0
64,Foyth,Villarreal,Defender,891,10,0,0,98.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,0.0,2.0,2.0,55.0,20.0,10.0,10.0,30.0,9.0,7.0,1.0,0.0,82.1,347.0,290.0,0.0,1.0,0.0,8.0
157,Fernando Costanza,Sheriff,Defender,540,6,0,0,64.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,1.0,1.0,39.0,19.0,13.0,6.0,39.0,6.0,8.0,2.0,0.0,65.5,136.0,92.0,18.0,11.0,2.0,4.0
293,Vidal,Inter,Midfielder,409,7,1,2,53.2,0.0,0.0,2.0,NaN,NaN,NaN,NaN,NaN,0.0,1.0,0.0,0.0,1.0,0.0,0.0,3.0,2.0,0.0,1.0,30.0,19.0,10.0,9.0,9.0,10.0,6.0,1.0,0.0,90.4,254.0,222.0,66.0,3.0,2.0,3.0
145,Álvarez,Ajax,Midfielder,558,7,0,0,73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,2.0,4.0,1.0,29.0,19.0,10.0,9.0,7.0,17.0,6.0,4.0,0.0,93.3,363.0,340.0,0.0,1.0,0.0,7.0
217,Sergio Busquets,Barcelona,Midfielder,487,6,0,0,63.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,1.0,1.0,29.0,19.0,9.0,10.0,3.0,9.0,14.0,1.0,0.0,89.0,382.0,340.0,0.0,0.0,0.0,16.0

In [142]:
m8.sort_values(by='yellow',ascending = False).head(10).dropna(axis=1)

,player_name,club,position,minutes_played,match_played,goals,assists,distance_covered,fouls_committed,fouls_suffered,red,yellow
229,Felipe,Atlético,Defender,472,7,0,0,51.4,7.0,2.0,3.0,2.0
275,Angeliño,Leipzig,Defender,432,5,0,3,50.7,4.0,2.0,2.0,1.0
56,Capoue,Villarreal,Midfielder,1046,12,2,4,130.9,19.0,17.0,3.0,1.0
291,Ahmedhodžić,Malmö,Defender,413,5,0,0,46.3,6.0,0.0,1.0,1.0
624,Emre Can,Dortmund,Defender,74,2,0,0,8.4,1.0,1.0,0.0,1.0
286,Wan0Bissaka,Man. United,Defender,419,6,0,0,45.9,4.0,2.0,0.0,1.0
374,Kessié,Milan,Midfielder,321,5,0,1,41.2,9.0,6.0,2.0,1.0
613,En0Nesyri,Sevilla,Forward,83,2,0,0,10.2,5.0,3.0,3.0,1.0
383,Welinton,Beşiktaş,Defender,313,4,0,0,33,6.0,1.0,1.0,1.0
367,Jordán,Sevilla,Midfielder,327,6,1,0,43.3,10.0,4.0,2.0,1.0

In [149]:
m8.loc[:,['player_name','club','goals']].sort_values(by= 'goals',ascending =False).head(15).style.background_gradient("Greens")

In [148]:
m8.loc[:,['player_name','club','saved','conceded','cleansheets']].sort_values(by= ['saved','conceded','cleansheets'],ascending =[False,True,False]).head(10)

          player_name         club  saved  conceded  cleansheets
0            Courtois  Real Madrid   61.0      14.0          5.0
54              Rulli   Villarreal   41.0      16.0          3.0
62        Vlachodimos      Benfica   38.0      17.0          5.0
259      Athanasiadis      Sheriff   29.0       8.0          1.0
166          Mignolet  Club Brugge   28.0      20.0          0.0
63              Oblak     Atlético   26.0      10.0          3.0
167             Musso     Atalanta   21.0      13.0          1.0
255  Ersin Destanoğlu     Beşiktaş   20.0      17.0          0.0
381            Dahlin        Malmö   19.0       8.0          0.0
120            De Gea  Man. United   19.0       9.0          1.0

In [153]:
m8.loc[:,['player_name','club','red']].sort_values(by= 'red',ascending =False).head(15).style.background_gradient("Wistia_r")

In [154]:
m8.loc[:,['player_name','club','yellow']].sort_values(by= 'yellow',ascending =False).head(15).style.background_gradient("Wistia_r")

In [157]:
m8.loc[:,['player_name','pass_accuracy','pass_attempted']].sort_values(by= ['pass_attempted','pass_accuracy'],ascending =[False,False]).head(15).style.background_gradient("Greens")

In [158]:
m8.columns

Index(['player_name', 'club', 'position', 'minutes_played', 'match_played',
       'goals', 'assists', 'distance_covered', 'corner_taken', 'offsides',
       'dribbles', 'saved', 'conceded', 'saved_penalties', 'cleansheets',
       'punches made', 'right_foot', 'left_foot', 'headers', 'others',
       'inside_area', 'outside_areas', 'penalties', 'total_attempts',
       'on_target', 'off_target', 'blocked', 'balls_recoverd', 'tackles',
       't_won', 't_lost', 'clearance_attempted', 'fouls_committed',
       'fouls_suffered', 'red', 'yellow', 'pass_accuracy', 'pass_attempted',
       'pass_completed', 'cross_accuracy', 'cross_attempted', 'cross_complted',
       'freekicks_taken'],
      dtype='object')

In [159]:
m8.insert(24,'on_target_rate',m8.on_target/m8.total_attempts)

In [165]:
m8.loc[:,['player_name','on_target_rate','total_attempts']].sort_values(by= ['total_attempts'],ascending =[False]).head(15).style.background_gradient("Greens")

In [166]:
m8.loc[:,['player_name','cross_attempted','cross_accuracy']].sort_values(by= ['cross_attempted'],ascending =[False]).head(15).style.background_gradient("Greens")

In [168]:
m8.loc[:,['player_name','saved','cleansheets']].sort_values(by = ['saved','cleansheets'],ascending =[False,False]).head(15).style.background_gradient('Greens')

In [170]:
m8.loc[:,['player_name','club','cross_attempted','cross_complted']].sort_values(by = ['cross_complted','cross_attempted'],ascending =[False,False]).head(15).style.background_gradient('Greens')